version: '3'
services:

  informix:
    image: ibmcom/informix-developer-database:12.10.FC11DE
    environment:
      - LICENSE=accept
    privileged: true
    ports:
      - 127.0.0.1:9088:9088
      - 127.0.0.1:9089:9089
    tty: true
    shm_size: 1gb

  aios:
    image: thinkbaer/aios:0.6.0
    ports:
      - 127.0.0.1:8118:8118
    links:
      - informix
